[package]
name = "clifford"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_macros = { path = "./proc_macros" }
num-traits = "0.2.15"

[[test]]
name = "cga_3d_tests"
required-features = ["cga_3d"]

[[test]]
name = "ga_3d_tests"
required-features = ["ga_3d"]

[features]
ga_3d = []
pga_3d = []
va_3d = []
cga_2d = []
cga_3d = []