[package]
name = "clifford"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_macros = { path = "./proc_macros" }
num-traits = "0.2.15"
num-sqrt = { path = "../num-sqrt" }
num-trig = { path = "../num-trig" }
f_zero = { path = "../f_zero", optional = true }
macros = { path = "./macros" }

[dev-dependencies]
criterion = "0.4.0"
rand = "0.8"
num-dual = { path = "../num-dual" }

#[[test]]
#name = "cga_3d_tests"
#required-features = ["cga_3d"]

[[test]]
name = "ga_3d_tests"
required-features = ["ga_3d"]

[[test]]
name = "pga_3d_tests"
required-features = ["pga_3d"]

[features]
ga_3d = []
pga_3d = []
cga_2d = []
cga_3d = []
dyn = ["f_zero"]

[[bench]]
name = "inverse"
harness = false

[[bench]]
name = "sandwich"
harness = false
