[package]
name = "clifford"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_macros = { path = "./proc_macros" }

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "mul"
harness = false

[features]
pga_3d = []
cga_2d = []
cga_3d = []