[package]
name = "clifford"
version = "0.1.0"
edition = "2021"
authors = ["Fraser Balch <fraser.balch@gmail.com>"]
keywords = ["clifford", "algebra", "geometric"]
license = "MIT"

[workspace]
members = ["macros", "algebra"]

[dependencies]
geo_traits = { git = "https://github.com/frsrblch/geo_traits", version = "0.4" }
macros = { path = "./macros" }

[[example]]
name = "ga_2d"

[dev-dependencies]
bytemuck = "1"
rand = "0.8"
