[package]
name = "clifford"
version = "0.1.0"
edition = "2021"
authors = ["Fraser Balch <fraser.balch@gmail.com>"]
keywords = ["clifford", "algebra", "geometric"]

[workspace]
members = ["macros", "algebra"]

[dependencies]
macros = { path = "./macros" }
