[package]
name = "macros"
version = "0.1.0"
edition = "2021"
authors = ["Fraser Balch <fraser.balch@gmail.com>"]
keywords = ["clifford", "algebra", "geometric"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "2"
algebra = { path = "../algebra" }
